version: "3.3"

services:
  app:
    build:
      context: .
    volumes:
      - ./dist:/app
    restart: on-failure
    command: ["/wait-for-it.sh", "db:3306", "--", "java","-jar", "demo-0.0.1-SNAPSHOT.jar"]

  db:
    image: mysql
    ports:
      - "3308:3306"
    env_file:
      - .env.db
    restart: on-failure
    volumes:
      - ./mysql:/var/lib/mysql

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf